### ISSUE TITLE
Feature: Polter Sense

### ISSUE THREAD

**Issue by ThijsvanDijk** [ApericotStudio/Poltergeist#105]
Polter Sense is a new vision system in which all interactables and throwables get a slight glimmer around them. Look at Witcher sensing for inspiration.

Criteria:
- When pressing RMB polter sense is activated
- When in polter sense mode interactables and throwables get a small glow around them.
- When aiming at an interactable or throwable it still highlights.
- Glow and highlight colors for Polter Sense
		- Purple: Interactable
		- Green: Throwable
- When aiming at an interactable show a prompt on screen that says something like "Press e to interact/possess"

Resources:
- [https://youtu.be/loF59NwRn9Q?feature=shared](url) 
- [https://youtu.be/Q3M0fqsjeuU?feature=shared](url)

**Comment by Jeroenvn** [comment]
## Outline version 1

Following this tutorial I made a simple shader which looks ok.
https://youtu.be/z3llR94ckbg?feature=shared

https://github.com/ApericotStudio/Poltergeist/assets/50752585/cb946cc3-70f9-472a-b7be-665b684cda98

Issues:
- Can't see outline when it's inside another object (happends in the video to the bottom outline in the game scene)
- It is a material that goes on an object piece, so you either need to put it on every piece or make an invisible box that has roundabout the same dimensions. Both having their own issues: the first way can show the highlight in places on the object and the second does not follow the actual shape of the object and is just a box
- There is also an issue of it scaling with the scale of the object itself

**Comment by Jeroenvn** [comment]
## Outline version 2

I have not created it but I would like to mention this tutorial.
https://www.youtube.com/watch?v=Q3M0fqsjeuU

Possible issues:
- It's on the object itself so it's not realy an "out"line
- Also scales with object itself
- And the biggest one: it might have weird interaction as it goes on the transform itself which if it has to go on each individual part would show the "out"line on each one of them

**Comment by Jeroenvn** [comment]
## Outline version 3

This time I've tried using the outline option from toonlink.
https://docs.unity3d.com/Packages/com.unity.toonshader@0.7/manual/GettingStarted.html

https://github.com/ApericotStudio/Poltergeist/assets/50752585/15d2f84c-21e7-481f-a3ff-177869cce9db

As you can see it looks exactly the same as the one from version 1.

There is one possible issue with version 1 that this might be able to solve might the need arise. And that is that if version 1 has outlines inside of the object because of geometry then toonlink might be able to fix that.
